---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/terraform-docs/terraform-docs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: 0643382b16ca523deb9c002434df95e825979a45  # frozen: v0.21.0
    hooks:
      - id: terraform-docs-go
        args:
          - "--config=.terraform-docs.yml"
          - "--lockfile=false"
          - "--recursive"
          - "--recursive-path=examples/"
          - "./"
