formatter: markdown table

header-from: .header.md

content: |-
  {{ .Header }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  escape: true
  indent: 2
  required: true
  type: true
