#!/usr/bin/env bash
# Copyright 2026 nnthanh101@gmail.com (oceansoft.io). Licensed under Apache-2.0. See LICENSE.
# Consumer project scaffolding generator
# Usage: MODULE=iam-identity-center ACCOUNT_ID=728863344838 bash scripts/project-init.sh
set -euo pipefail

# ─── inputs ───────────────────────────────────────────────────────────────────
MODULE="${MODULE:-}"
ACCOUNT_ID="${ACCOUNT_ID:-}"
REGION="${REGION:-ap-southeast-2}"
PROFILE="${PROFILE:-}"
FORCE="${FORCE:-false}"
EVIDENCE_DIR="${EVIDENCE_DIR:-tmp/terraform-aws}"

DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# ─── validation ───────────────────────────────────────────────────────────────
if [ -z "$MODULE" ]; then
  echo "ERROR: MODULE is required (e.g. MODULE=iam-identity-center)" >&2
  exit 1
fi
if [ -z "$ACCOUNT_ID" ]; then
  echo "ERROR: ACCOUNT_ID is required (12-digit AWS account ID)" >&2
  exit 1
fi
if ! echo "$ACCOUNT_ID" | grep -qE '^[0-9]{12}$'; then
  echo "ERROR: ACCOUNT_ID must be exactly 12 digits, got: $ACCOUNT_ID" >&2
  exit 1
fi

MODULE_DIR="modules/${MODULE}"
PROJECT_DIR="projects/${MODULE}"
MODULE_OUTPUTS="${MODULE_DIR}/outputs.tf"

if [ ! -d "$MODULE_DIR" ]; then
  echo "ERROR: Module directory not found: $MODULE_DIR" >&2
  exit 1
fi

# HCL identifier: hyphens → underscores (iam-identity-center → iam_identity_center)
MODULE_SLUG=$(echo "$MODULE" | sed 's/-/_/g')

BUCKET="tfstate-${ACCOUNT_ID}-${REGION}"
STATE_KEY="projects/${MODULE}/terraform.tfstate"

COPYRIGHT="# Copyright 2026 nnthanh101@gmail.com (oceansoft.io). Licensed under Apache-2.0. See LICENSE."

SKIP=0; WRITTEN=0; BACKED=0
echo "=== project:init [MODULE=${MODULE}] ==="

mkdir -p "$PROJECT_DIR" "$EVIDENCE_DIR/evidence"

# ─── helper: write_file ────────────────────────────────────────────────────────
write_file() {
  local path="$1"
  local content="$2"
  local label="$3"

  if [ -f "$path" ] && [ "$FORCE" != "true" ]; then
    echo "SKIP: $label ($path already exists — use FORCE=true to overwrite)"
    SKIP=$((SKIP + 1))
    return
  fi

  if [ -f "$path" ] && [ "$FORCE" = "true" ]; then
    cp "$path" "${path}.bak"
    echo "BAK:  $label (${path}.bak)"
    BACKED=$((BACKED + 1))
  fi

  printf '%s\n' "$content" > "$path"
  echo "WRITE: $label ($path)"
  WRITTEN=$((WRITTEN + 1))
}

# ─── 1. backend.tf ────────────────────────────────────────────────────────────
BACKEND_CONTENT="${COPYRIGHT}
# ADR-006: S3 native locking (use_lockfile = true), no DynamoDB

terraform {
  backend \"s3\" {
    region       = \"${REGION}\"
    bucket       = \"${BUCKET}\"
    key          = \"${STATE_KEY}\"
    use_lockfile = true
  }
}"
write_file "${PROJECT_DIR}/backend.tf" "$BACKEND_CONTENT" "backend.tf"

# ─── 2. variables.tf ──────────────────────────────────────────────────────────
VARIABLES_CONTENT="${COPYRIGHT}

variable \"aws_region\" {
  description = \"AWS region for state backend reference\"
  type        = string
  default     = \"${REGION}\"
}"
write_file "${PROJECT_DIR}/variables.tf" "$VARIABLES_CONTENT" "variables.tf"

# ─── 3. outputs.tf (auto-generated from module outputs) ───────────────────────
if [ -f "$MODULE_OUTPUTS" ]; then
  OUTPUTS_BODY=""
  while IFS= read -r line; do
    if echo "$line" | grep -qE '^output "[^"]+" \{'; then
      OUT_NAME=$(echo "$line" | sed 's/output "\([^"]*\)".*/\1/')
      OUT_DESC=""
    fi
    if echo "$line" | grep -q 'description'; then
      OUT_DESC=$(echo "$line" | sed 's/.*description *= *"\([^"]*\)".*/\1/')
    fi
    if echo "$line" | grep -qE '^\}' && [ -n "${OUT_NAME:-}" ]; then
      OUTPUTS_BODY="${OUTPUTS_BODY}
output \"${OUT_NAME}\" {
  description = \"${OUT_DESC}\"
  value       = module.${MODULE_SLUG}.${OUT_NAME}
}
"
      OUT_NAME=""
    fi
  done < "$MODULE_OUTPUTS"

  OUTPUTS_CONTENT="${COPYRIGHT}
# Auto-generated from ${MODULE_OUTPUTS} by scripts/project-init.sh

output \"account_id\" {
  description = \"AWS account ID (for audit trail)\"
  value       = data.aws_caller_identity.current.account_id
}
${OUTPUTS_BODY}"
else
  OUTPUTS_CONTENT="${COPYRIGHT}
# WARNING: ${MODULE_OUTPUTS} not found — manual outputs.tf required

output \"account_id\" {
  description = \"AWS account ID (for audit trail)\"
  value       = data.aws_caller_identity.current.account_id
}"
fi
write_file "${PROJECT_DIR}/outputs.tf" "$OUTPUTS_CONTENT" "outputs.tf"

# ─── 4. main.tf scaffold ──────────────────────────────────────────────────────
MAIN_CONTENT="${COPYRIGHT}
# Consumer project: ${MODULE}
# Generated by scripts/project-init.sh — customise module inputs before applying.

data \"aws_caller_identity\" \"current\" {}

module \"${MODULE_SLUG}\" {
  source = \"../../modules/${MODULE}\"

  # TODO: populate module-specific input variables
  # See modules/${MODULE}/variables.tf for required inputs
}"
write_file "${PROJECT_DIR}/main.tf" "$MAIN_CONTENT" "main.tf"

# ─── 5. terraform fmt + init + validate ──────────────────────────────────────
FMT_OK="false"; INIT_OK="false"; VALIDATE_OK="false"
echo ""
echo "=== Post-generation validation ==="

if command -v terraform >/dev/null 2>&1; then
  cd "$PROJECT_DIR"

  if terraform fmt -check . >/dev/null 2>&1; then
    echo "PASS: terraform fmt -check"
    FMT_OK="true"
  else
    echo "FIX:  terraform fmt (auto-formatting)"
    terraform fmt . >/dev/null 2>&1
    FMT_OK="true"
  fi

  if terraform init -backend=false -input=false >/dev/null 2>&1; then
    echo "PASS: terraform init -backend=false"
    INIT_OK="true"
  else
    echo "WARN: terraform init -backend=false failed (module may need registry auth)"
  fi

  if [ "$INIT_OK" = "true" ] && terraform validate >/dev/null 2>&1; then
    echo "PASS: terraform validate"
    VALIDATE_OK="true"
  else
    echo "WARN: terraform validate skipped (init required first)"
  fi

  cd - >/dev/null
else
  echo "SKIP: terraform not found (run inside devcontainer for validation)"
fi

# ─── evidence ─────────────────────────────────────────────────────────────────
EVIDENCE_FILE="$EVIDENCE_DIR/evidence/project-init-${MODULE}-${DATE}.json"
cat > "$EVIDENCE_FILE" <<EJSON
{
  "timestamp": "${TIMESTAMP}",
  "module": "${MODULE}",
  "project_dir": "${PROJECT_DIR}",
  "account_id": "${ACCOUNT_ID}",
  "region": "${REGION}",
  "bucket": "${BUCKET}",
  "state_key": "${STATE_KEY}",
  "force": ${FORCE},
  "files_written": ${WRITTEN},
  "files_skipped": ${SKIP},
  "files_backed_up": ${BACKED},
  "fmt_passed": ${FMT_OK},
  "init_passed": ${INIT_OK},
  "validate_passed": ${VALIDATE_OK},
  "script": "scripts/project-init.sh v1.1.0"
}
EJSON

echo ""
echo "Result: ${WRITTEN} written, ${SKIP} skipped, ${BACKED} backed up"
echo "Evidence: ${EVIDENCE_FILE}"
echo "PASSED: project:init [MODULE=${MODULE}]"
